name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_REPO_NAME }}
      TAG_1 : ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_REPO_NAME }}:${{ github.sha }}
      TAG_2: ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_REPO_NAME }}:latest

    steps:
    - name: Azure Container Registry Login
      run: echo ${{ secrets.ACR_LOGIN_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_LOGIN_USERNAME }} --password-stdin

    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag ${{ env.TAG_1 }} --tag ${{ env.TAG_2 }} --file ./DOCKERFILE .

    - name: Push tag 1
      run: docker push ${{ env.TAG_1 }}

    - name: Push tag 2
      run: docker push ${{ env.TAG_2 }}
